# Generated by Django 4.2.15 on 2024-08-29 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('select_bach', models.CharField(blank=True, choices=[('B1', 'Bach 1'), ('B2', 'Bach 2'), ('B3', 'Bach 3'), ('B4', 'Bach 4'), ('B5', 'Bach 5')], max_length=2, null=True)),
                ('bach_time', models.DateField(blank=True, null=True)),
                ('fees', models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'paid')], max_length=10, null=True)),
                ('attendence', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
