# Generated by Django 4.2.15 on 2024-08-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAdmin',
        ),
    ]
