# Generated by Django 4.2.15 on 2024-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
