# Generated by Django 4.2.15 on 2024-08-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bach_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
