# Generated by Django 4.2.15 on 2024-08-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_student_bach_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='select_department',
            field=models.CharField(blank=True, choices=[('DS', 'Data Science'), ('flutter', 'Flutter'), ('DA', 'Data Analytics'), ('py', 'Python'), ('ASP', 'ASP.NET')], max_length=10, null=True),
        ),
    ]
