# Generated by Django 4.2.15 on 2024-08-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student_select_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='select_department',
            new_name='department',
        ),
    ]
