# Generated by Django 4.2.15 on 2024-08-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_select_department_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('DataScience', 'Data Science'), ('flutter', 'Flutter'), ('DataAnalytics', 'Data Analytics'), ('python', 'Python'), ('ASP.NET', 'ASP.NET')], max_length=20, null=True),
        ),
    ]
