# Generated by Django 4.2.15 on 2024-08-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_student_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='select_bach',
            new_name='bach',
        ),
    ]
