# Generated by Django 4.2.15 on 2024-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_batch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
