# Generated by Django 4.2.15 on 2024-08-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_batch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.department'),
        ),
    ]
